"""Agent contracts and response validation layer for Architecture A (Single-Agent Baseline)."""

from __future__ import annotations

import logging
from typing import Any
from pydantic import Field

from src.contracts import EvidenceItem, ProcurementDecision, RunTelemetry

logger = logging.getLogger(__name__)


class SingleAgentResponse(ProcurementDecision):
    """Structured response contract for Architecture A (Single-Agent Baseline).

    Inherits all fields from ProcurementDecision to maintain 100% backward compatibility
    with the evaluation harness, while exposing rich qualitative narrative and
    clarification questions generated by the agent.
    """
    summary: str = Field(
        default="",
        description="Executive summary of the procurement request and triage assessment",
    )
    reasoning: str = Field(
        default="",
        description="Qualitative reasoning regarding business fit, catalog overlap, risk, and policy",
    )
    catalog_fit_analysis: str = Field(
        default="",
        description="Specific comparison of requested product against existing software inventory",
    )
    clarification_questions: list[str] = Field(
        default_factory=list,
        description="Targeted follow-up questions when information is missing",
    )


def validate_and_assemble_response(
    llm_payload: dict[str, Any] | None,
    decision: ProcurementDecision,
    telemetry: RunTelemetry,
) -> SingleAgentResponse:
    """Validate LLM output against authoritative deterministic decision and assemble final response.

    STRICT SAFETY INVARIANTS ENFORCED:
    1. final.recommendation == decision.recommendation (LLM cannot alter recommendation)
    2. final.required_approvals == decision.required_approvals (LLM cannot alter approval roster)
    3. final.missing_information == decision.missing_information (LLM cannot fabricate missing data)
    4. final.risk_flags == decision.risk_flags (LLM cannot clear risk flags)
    5. final.human_review_required == True (LLM cannot bypass human review)
    6. final.evidence == decision.evidence (Evidence grounding preserved)
    7. final.next_step == decision.next_step (Authoritative routing instruction preserved)
    """
    if llm_payload is None:
        llm_payload = {}

    # Extract qualitative fields from LLM payload
    raw_summary = str(llm_payload.get("summary", "")).strip()
    raw_reasoning = str(llm_payload.get("reasoning", "")).strip()
    raw_catalog_fit = str(llm_payload.get("catalog_fit_analysis", "")).strip()
    raw_questions = llm_payload.get("clarification_questions", [])

    # Defend against LLM hallucinating approval authority
    forbidden_tokens = ["auto-approved", "purchase approved", "automatically approved", "override policy"]
    for token in forbidden_tokens:
        if token in raw_summary.lower():
            logger.warning("Sanitizing unauthorized approval claim in LLM summary.")
            raw_summary = raw_summary.replace(token, "[unauthorized claim removed]")
        if token in raw_reasoning.lower():
            logger.warning("Sanitizing unauthorized approval claim in LLM reasoning.")
            raw_reasoning = raw_reasoning.replace(token, "[unauthorized claim removed]")

    # Provide high-quality defaults if LLM generated empty strings
    if not raw_summary:
        raw_summary = (
            f"Procurement triage for request {decision.request_id} ({decision.recommendation}): "
            f"Requires approval by {', '.join(decision.required_approvals) if decision.required_approvals else 'Procurement'}."
        )

    if not raw_reasoning:
        risk_str = ", ".join(decision.risk_flags) if decision.risk_flags else "none"
        raw_reasoning = (
            f"The request was evaluated under corporate procurement policy. "
            f"Identified risk factors: {risk_str}. "
            f"Decision precedence mandates state {decision.recommendation}."
        )

    if not raw_catalog_fit:
        if "existing_tool_overlap" in decision.risk_flags:
            raw_catalog_fit = "Existing tools in the corporate catalog share functional category overlap. Review required."
        else:
            raw_catalog_fit = "No conflicting software overlap identified in current active inventory."

    # Validate and normalize clarification questions
    questions: list[str] = []
    if isinstance(raw_questions, list):
        questions = [str(q).strip() for q in raw_questions if str(q).strip()]

    # Guarantee clarification questions exist if information is missing
    if decision.missing_information and not questions:
        for missing_item in decision.missing_information:
            questions.append(f"Please provide clarification or documentation for: {missing_item}.")

    # Assemble and return verified SingleAgentResponse
    return SingleAgentResponse(
        request_id=decision.request_id,
        recommendation=decision.recommendation,  # STRICT: Invariant
        evidence=decision.evidence,              # STRICT: Invariant
        required_approvals=list(decision.required_approvals),  # STRICT: Invariant
        missing_information=list(decision.missing_information),# STRICT: Invariant
        risk_flags=list(decision.risk_flags),    # STRICT: Invariant
        next_step=decision.next_step,            # STRICT: Invariant
        human_review_required=True,              # STRICT: Policy Invariant
        telemetry=telemetry,
        summary=raw_summary,
        reasoning=raw_reasoning,
        catalog_fit_analysis=raw_catalog_fit,
        clarification_questions=questions,
    )
